stages:
  - reseau

variables:
  PATH_TO_RESEAU: "/builds/projet-integrateur-5b/pi_carcassonne"
  RESEAU_DIRECTORY: "Reseau"
  RESEAU_OBJECTS_DIRECTORY: '$RESEAU_DIRECTORY/obj'
  RESEAU_NUGET_PACKAGES_DIRECTORY: '$RESEAU_DIRECTORY/.nuget'

cache:
  # Per-stage and per-branch caching.
  key: "$CI_JOB_STAGE-$CI_COMMIT_REF_SLUG"
  paths:
    - '$RESEAU_OBJECTS_DIRECTORY/project.assets.json'
    - '$RESEAU_OBJECTS_DIRECTORY/*.csproj.nuget.*'
    - '$RESEAU_NUGET_PACKAGES_DIRECTORY'
  policy: pull-push

reseau:build:
  image: mcr.microsoft.com/dotnet/sdk
  stage: reseau
  script:
    - "cd $RESEAU_DIRECTORY"
    - "dotnet restore"
    - "dotnet build"
  only:
    - reseau

reseau:style:
  image: mcr.microsoft.com/dotnet/sdk
  stage: reseau
  needs: ["reseau:build"]
  script:
    - "cd $RESEAU_DIRECTORY"
    - "dotnet tool update -g dotnet-format"
    - "dotnet format --verify-no-changes --verbosity diag"
  only:
    - reseau

reseau:test:
  image: mcr.microsoft.com/dotnet/sdk
  stage: reseau
  needs: ["reseau:build"]
  script:
    - "cd $RESEAU_DIRECTORY"
    - "dotnet restore"
    - "dotnet test"
  only:
    - reseau

reseau:coverage:
  image: mcr.microsoft.com/dotnet/sdk
  stage: reseau
  script:
    - "cd $RESEAU_DIRECTORY"
    - "dotnet test --collect:\"XPlat Code Coverage\" -r cobertura --no-build"
    - "dotnet tool update -g dotnet-reportgenerator-globaltool"
    - "export PATH=\"$PATH:/root/.dotnet/tools\""
    - "reportgenerator -reports:\"coverage/*/coverage.cobertura.xml\" -targetdir:\"coverage/report\" -reporttypes:\"TextSummary;Html\""
    - "cat Reports/Coverage/Summary.txt"
  coverage: /^\s*Line coverage:\s*g\d+.\d+\%$/
  artifacts:
    paths:
      - coverage/*/coverage.cobertura.xml
      - coverage/report/Summary.txt
      - coverage/report/Cobertura.xml
    reports:
      cobertura: coverage/report/Cobertura.xml
  only:
    - reseau