stages:
  - reseau

variables:
  PATH_TO_RESEAU: "/builds/projet-integrateur-5b/pi_carcassonne"
  RESEAU_DIRECTORY: "Reseau"
  RESEAU_OBJECTS_DIRECTORY: '$RESEAU_DIRECTORY/obj'
  RESEAU_NUGET_PACKAGES_DIRECTORY: '$RESEAU_DIRECTORY/.nuget'

cache:
  # Per-stage and per-branch caching.
  key: "$CI_JOB_STAGE-$CI_COMMIT_REF_SLUG"
  paths:
    - '$RESEAU_OBJECTS_DIRECTORY/project.assets.json'
    - '$RESEAU_OBJECTS_DIRECTORY/*.csproj.nuget.*'
    - '$RESEAU_NUGET_PACKAGES_DIRECTORY'
  policy: pull-push
  
reseau:build:
  image: mcr.microsoft.com/dotnet/sdk
  stage: reseau
  script:
    - "cd $RESEAU_DIRECTORY"
    - "dotnet restore"
    - "dotnet build"
  only:
    - reseau

reseau:style:
  image: mcr.microsoft.com/dotnet/sdk
  stage: reseau
  needs: ["reseau:build"]
  script:
    - "cd $RESEAU_DIRECTORY"
    - "dotnet tool update -g dotnet-format"
    - "dotnet format --verify-no-changes --verbosity diag"
  only:
    - reseau

reseau:test:
  image: mcr.microsoft.com/dotnet/sdk
  stage: reseau
  needs: ["reseau:build"]
  script:
    - "cd $RESEAU_DIRECTORY"
    - "dotnet restore"
    - "dotnet test"
  only:
    - reseau      
      
test-with-coverage:
  image: mcr.microsoft.com/dotnet/sdk
  stage: reseau
  variables:
    CI_PROJECT_DIR: "."
    CONFIGURATION: "Debug"
    COVERAGE_FLAG: "XPlat Code Coverage"
  script:
    - "cd $RESEAU_DIRECTORY"
    - 'dotnet test
            -r $CI_PROJECT_DIR/cobertura
            --collect:"$COVERAGE_FLAG"'
    - "chmod +x ./scripts/print-dotnet-coverage.sh"
    - "./scripts/print-dotnet-coverage.sh $CI_PROJECT_DIR/cobertura"
  coverage: /TOTAL_COVERAGE=(\d+.\d+)/
  artifacts:
    paths:
      - $CI_PROJECT_DIR/cobertura/*/coverage.cobertura.xml
    reports:
      cobertura:
        - $CI_PROJECT_DIR/cobertura/*/coverage.cobertura.xml